// Auto-generated by make — do not edit
let buildVersion = "1.8.3"
let buildCommit = "52e4f2e"
let buildBranch = "main"
let buildDate = "2026-07-09 17:22:49 UTC"
let buildSwiftVersion = "6.3.3"
let buildOS = "macOS 26.5.2"
