// Auto-generated by make — do not edit
let buildVersion = "1.7.1"
let buildCommit = "04b6eac"
let buildBranch = "main"
let buildDate = "2026-07-02 13:10:40 UTC"
let buildSwiftVersion = "6.3.3"
let buildOS = "macOS 26.5.2"
