// Auto-generated by make — do not edit
let buildVersion = "1.7.0"
let buildCommit = "4d39f96"
let buildBranch = "main"
let buildDate = "2026-07-02 06:28:37 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
